version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: church_app_db
    environment:
      POSTGRES_DB: church_app
      POSTGRES_USER: church_user
      POSTGRES_PASSWORD: church_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: